apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXX
    server: https://graphite-1.nancy.grid5000.fr:6443
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: kube-admin-local
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: kube-admin-local
  user:
    client-certificate-data: XXX
    client-key-data: XXX
